name: Update Main Leaderboard

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Replace with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run the Python script
      run: python path/to/your/script.py

    - name: Commit files
      run: |
        git config --global user.name "kushal-10"
        git config --global user.email "kushalkoshti11@gmail.com"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update main_leaderboard.md"
        git push https://<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>@github.com/kushal-10/temp2.github.io.git main
